---
- import_role:
    name: aws
  vars:
    dns_record_list:
      - name: "{{ private_dns }}.{{ private_domain }}"
        zone: "{{ private_domain }}"
        type: A
        value: "{{ private_ip }}"
        private: true
        ttl: 120

- name: Include opinion role
  ansible.builtin.include_role:
    name: opinion
  vars:
    user: "{{ app_user }}"
    group: "{{ app_group }}"
    collaboration_base: "{{ opinion_base_path }}"
    discord_webhook_error_log: "{{ discord_webhooks.apilog | default(discord_webhooks.default) }}"