name: opinion on tag

on:
  push:
    branches: 
      - 'test-workflow'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  goldenimage:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/goldenimage-workflow.yml@default
    with:
      S3_BASE_PATH: "s3://bootstrap-opinion-stg/playbooks"
      ROLE: "arn:aws:iam::992382682634:role/ansible-playbook-workflow-role"
      REGION: "il-central-1"
      CPU_ARCH: "arm64"
      OS: "amzn2023"
      APP: "opinion"
      TOOLKIT_VERSION: "default"